/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xwc_com_ndkdemo_JniTest */

#ifndef _Included_xwc_com_ndkdemo_JniTest
#define _Included_xwc_com_ndkdemo_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xwc_com_ndkdemo_JniTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xwc_com_ndkdemo_JniTest_getString
  (JNIEnv *, jobject);

/*
 * Class:     xwc_com_ndkdemo_JniTest
 * Method:    plus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_xwc_com_ndkdemo_JniTest_plus
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
